sudo: required

services:
  - docker

before_install:
  - docker image build -t chouffe/docker-react -f Dockerfile.dev .

script:
  - docker container run --rm chouffe/docker-react npm run test -- --coverage
